export const projectPage = {
  projectsPage: '//p[text()="Explore Projects"]',
  allProjectBtn: 'mat-button-toggle[value="all"]',
  developmentalPrjectBtn: 'mat-button-toggle[value="developmental"]',
  MatureProjectsBtn: 'mat-button-toggle[value="mature"]',
  developmentTag: '//div[text()=" Developmental "]',
  projectDetail: '//label[text()="Detail"]',
  projectInstance: '//section[@class="PropertyListing mb-5"]/div/div[1]',
  exploreProject: '(//button[text()=" Explore "])[1]',
  purchaseNowBtn: '(//button[text()=" Purchase Now "])[1]',
  downloadHandbookBtn: '//a[text()="Download Handbook"]',
  projectStatus: '//h3[text()=" Project Stats "]',
  developmentStatus: '//h3[text()="Development Round Stats"]',
  purchaseAreaBtn: '(//button[text()="Purchase Now"])[2]',
  projectPlan: '[class*="card-body"]',
  pledgeAreaInput: '[formcontrolname="pledgeArea"]',
  selectUnit: '[class="select-unit"]',
  ownershipHeading: 'p[class="heading"]',
  orderSummary: '[class="summaryDv"]',
  purchaseBtn: '//span[text()="Purchase Now"]',
  pledgeRequestSubmitted: '[class="headerDv"] h2',
  projectsName: "div h2",
  remindMeBtn: ".btn_blue.text-nowrap",
  areaWarning: 'small[class="ng-star-inserted"]',
  areaInput: 'input[id*="mat-input-"]',
  heading: '[class="heading"]',
  drawerMenuBtn: '[class="menuBtnMobile"]',
  projectsTab: '//span[text()="Projects"]',
  popupContainer: '[class*="mat-dialog-container"]',
  acceptCheckbox: "[class=mat-checkbox-inner-container]",
  toastMessage: '[id="toastr-container"]',
  backToTopBtn: ".btn_blue_outline",
};
