export const transferArea = {
  transferArea: '//span[text()="Transfer Area"]',
  heading: '[class*="heading"]',
  tbasList: '[class="mat-tab-labels"]',
  table: '[class="table tbl_basic"]',
  tableBody: '[class="table tbl_basic"] tbody',
  tableRow: '//table[@class="table tbl_basic"]//tbody/tr[1]',
  popupContainer: '[class*="mat-dialog-container"]',
  searchInput: 'input[id="searchTable"]',
  newrecipientBtn: '//button[text()="New Recipient"]',
  walletStatus: '[class="input-group-append"]',
  recipientNameInput: '[formcontrolname="recipientField"]',
  cancelBtn: '//button[text()="Cancel"]',
  saveBtn: '//button[text()="Save"]',
  successMessage: '[id="toastr-container"] [class*="toastr-success"]',
  meatballBtn: 'td [class*="dropdown-toggle"]',
  dropdownMenu: '[class="dropdown"] [class*="dropdown-menu"]',
  actionBtns: '[class="dropdown"] [class*="dropdown-menu"] button',
  yesBtn: '//button[text()=" Yes "]',
  transferAreaBtn: '//button[text()="Transfer Area"]',
  checkbox: '[class="mat-checkbox-inner-container"]',
  getStartedBtn: '//button[text()="Get Started"]',
  dropdownBtn: '[class="ng-arrow-wrapper"]',
  dropdownItems: '[class*="ng-dropdown-panel-items"] [role="option"]',
  areaInput: '[formcontrolname="area"]',
  walletAddressInput: '[formcontrolname="walletAddress"]',
  transferNowBtn: '//button[text()="Transfer Now"]',
  firstTransferBtn: '//button[text()="Make your first transfer"]',
  summaryHeading: '//p[text()="Summary"]',
};
