export const holdersListPage = {
  holdersListTab: '//span[text()="Holders List"]',
  holdersBtn: '(//div[@class="mat-tab-labels"]//div)[3]',
  searchInput: 'input[type="search"]',
  tablerow: "tbody tr",
  transferDetail: '[class*="mat-row cdk-row"]',
  roleFilterDropDown: '(//*[@class="ng-star-inserted"]//ng-select)[2]',
  roleFilterText: '[class*="ng-value-label"]',
  filtersList: '[class*="ng-option-label"]',
  projectFilterdropdown: '(//div[@class="ng-value-container"])[1]',
  roleFilterdropdown: '(//div[@class="ng-value-container"])[2]',
  filterItems: '[class*="ng-dropdown-panel-items"] [role="option"]',
  syncTime: '[class*="alert show app-alert"] span',
  syncNowBtn: '[class*="alert show app-alert"] button',
  toastMessage: '[class*="mat-snack-bar-container"]',
  senderWalletID: "//tbody//td[3]//p",
  recieverWalletID: "//tbody//td[4]//p",
  holderWalletId: "//tbody//td[2]//p",
  usersToggleBtn: 'mat-button-toggle[value="user"]',
  senderName: "//tbody//td[3]//span",
  recieverName: "//tbody//td[4]//span",
  holdersName: "//tbody//td[2]//span",
  investorDetailHeader: ".navbar-menu ol li span",
  backBtn: '(//div[contains(@class, "navbar-menu")]//button)[1]',
  roleIdentify: 'tbody tr [class*="pill "]',
};
