export const propPage = {
  propertiesTab: '//span[text()="Properties"]',
  approvalRequestTab: '//span[text()="Approval Requests"]',
  projectHeading: '[class="text fs-16 font-m mb-3"]',
  heading: '[class*="heading "]',
  projectDropdownBtn: '[class="ng-arrow-wrapper"]',
  dropdownPanl: '[role="listbox"]',
  projectsList: '[role="listbox"] [role="option"]',
  propertyName: '[class="propertyName"]',
  statusContent: '[class*="mpd-item col-md-3"]',
  toogleBtn: '[class*="mat-button-toggle-button "]',
  roundstatusBar: '[class*="mpd-item col-md-3"] [class="progress-bar"]',
  statusMeetball: '(//button[contains(@class,"dropdown-toggle ")])[2]',
  meeballBallMenu: '[class*=" dropdown-menu show"] button',
  editDetailIcon: '[class="far fa-edit"]',
  endDateInput: 'input[formcontrolname="endDate"]',
  rateInput: 'input[formcontrolname="rate"]',
  tickIcon: '[class="fas fa-check"]',
  applyOnlyBtn: '//button[contains(text(), "Apply only on this")]',
  activityLog: 'tbody [role="row"]',
  activityDetails: '[class="right-panel"]',
  statsPopup: '[class*="mat-dialog-container "]',
  expandIcon: '[class*=" uil-expand-arrows-alt "]',
  roundStatsChart: '[class*="mat-dialog-container "] app-round-detail-graph',
  progressionChart: '[class*="mat-dialog-container "] highcharts-chart',
  projectTabs: '[routerlinkactive="active"]',
  tableRow: 'tbody [role="row"]',
  gallaryImages: '[class="property-images"] [class="images"]',
  aboutContainer: '//p[text()="About"]',
  roundStatsHeading: '//p[text()= "Round Stats"]',
  nextRoundBtn: '//button[contains(text(),"Next Round ")]',
  previousRoundBtn: '[class="btn btn-secondary mr-2"]',
  milestoneDetail: '[class="right-panel"]',
  meetBall: '(//button[contains(@class,"dropdown-toggle ")])[2]',
  progressRound:
    '(//div[contains(@class, "circle-progressbar")]//ancestor::tr)[1]',
  progressMilestone:
    '(//div[contains(@class, "circle-progressbar")]//ancestor::tr)[1]',
  milestoneStausDropdown: '[class="ng-arrow-wrapper"]',
  milestoneStatusOption: '[aria-label="Options list"] [role="option"]',
  progressBar: 'span[role="slider"]',
  rightsideModal: '[class="right-sidebar"]',
  updateNowBtn: '//button[contains(text(), "Update Now")]',
  toastMessage: '[class*="mat-snack-bar-container"]',
  progressInput: 'div[class="input w-25"] input',
  statusTitle: '[class="ng-value-container"] [class*="pill-theme"]',
  scheduleMilestone:
    '(//span[contains(@class, "rounded-icon pill-secondary")]//ancestor::tr)[1]',
  creatMilestoneBtn: '//button[contains(text(),"Create Milestone")]',
  createNowBtn: '//button[contains(text(),"Create Now")]',
  titleInput: 'input[formcontrolname="title"]',
  descriptionInput: 'textarea[formcontrolname="description"]',
  weightageInput: 'input[formcontrolname="weightage"]',
  startDate: 'input[formcontrolname="startDate"]',
  completionDate: 'input[formcontrolname="completionDate"]',
  deleteBtn:
    '//div[@class="right-sidebar"]//button[contains(text(), "Delete")]',
  completedMilestone:
    '//span[contains(@class,"pill-success-light")]//ancestor::tr',
  saveBtn: '//button[contains(text(), "Save")]',
  completedRound: '//span[contains(@class,"pill-success-light")]//ancestor::tr',
  lockedRound:
    '//span[@class="check-circle sm ng-star-inserted"]//ancestor::tr',
  unlockRoundBtn: '//button[contains(text(), "Unlock Round")]',
  passwordInput: 'input[formcontrolname="etherPassword"]',
  daysDropdown: '(//div[@class="ngb-menu dropdown"]//button[contains(@class, "dropdown-toggle")])[1]',
  projectsFilter: '(//div[contains(@class, "app-ngbDropdown")])[3]',
  requestStatusTabs: '[class="mat-tab-list"] [role="tab"]',
  requestTable: '[role="table"]',
  projectFilterOption: '[class*="fc-item"] mat-checkbox',
  applyBtn: '//button[contains(text(), "Apply")]',
  projectNameIndex: '//tbody//td[2]//span',
  searchInput: '[class="app-content"] input[type="search"]',
  usernameIndex: '//tbody//td[3]//div[contains(@class, "text")]',
  userIdindex: '//tbody//td[3]//div[contains(@class, "pill")]',
  phoneNumIndex: '//tbody//td[4]//p',
  proceedBtn: '//button[contains(text(), "Proceed")]',
  approveBtn: '//button[contains(text(), "Approve")]',
  doneBtn: '//button[contains(text(), "Done")]',
  requestMeetball: '//td//div[@class="ngb-menu dropdown"]//button',
  requestMenuBtn: '(//div[contains(@class, "dropdown-menu")])[9]//button',
  discardRequestBtn: '//div[@class="right-sidebar"]//button[contains(text(), "Discard Request")]',
  noteInput: 'textarea[type="text"]',
  allowAccessBtn: '//button[contains(text(), "Allow Access ")]',
  accessOptionBtn: '[class="sidebar-content"] button',
  searchInvetor: '[formcontrolname="investor"]',
  searchResult: '//div[contains(@class, "user-item")]',
};
