export const rentalPage = {
  rentalDistributionTab: '//span[text()="Rental Distribution"]',
  heading: '[class*="heading "]',
  applyBtn: '//button[contains(text(), "Apply")]',
  tableRow: 'tbody[role="rowgroup"] tr',
  projectNameindex: '//tbody[@role="rowgroup"]//tr[1]//td[1]',
  projectFilterBtn: '//button[contains(text(), "Projects:")]',
  dropDownMenu: '[class*=" dropdown-menu "]',
  projectFilterItems:
    '[class="checkbox-column"] [class*="fc-item"] mat-checkbox',
  noRentalDisbursments: '[class="text-center"] p',
  generatebatchReportBtn: '//span[text()="Generate Batch Report"]',
  batchReportItem: '//button//div[contains(text(), "Batch")]',
  toastMessage: '[class*="mat-snack-bar-container"]',
  checkInvoice: '//tbody[@role="rowgroup"]//tr//td[1]',
  clearSelectionBtn: '//button[contains(text(), "Clear Selection")]',
  generateInvoiceModalBtn:
    '(//button[contains(@class, "btn")][contains(text(), "Generate Invoice")])[2]',
  generateInvoiceModal: '(//div[@class="right-sidebar right-sidebar-lg"])[1]',
  doneScreen: '[class*="done-screen "]',
  meatballBtn: '//table//button[contains(@class, "dropdown-toggle")]',
  generateInvoiceAction: '[class*=" dropdown-menu show"] li',
  payoutCheckBox: "tbody mat-checkbox",
  checkAllpayouts: "(//thead//mat-checkbox)[1]",
  filterBtn: '//div[@class="d-block"]//button[contains(text(), "Filters ")]',
  payoutFilters:
    '//div[contains(@class, "filter-container")]//div[contains(@class, "dropdown-toggle")]',
  filterCheckItems: '[class*="fc-item "] mat-checkbox',
  resetFilterBtn: '//button[contains(text(), "Reset Filters")]',
  bankNameIndex: "//tbody//tr//td[8]",
  payoutStatusTabs: '[class="mat-tab-labels"] [role="tab"]',
  batchFiulterItems: '[class*=" dropdown-menu show"] button',
  revertToDUeBtn: '//button[contains(text(), "Revert to Due")]',
  revrtModal:
    '(//div[@class="right-sidebar"]//div[@class="sidebar-content"])[3]',
  reasonDropdown: 'ng-select[placeholder="Select Reason"]',
  reasonsOption: '[class*="ng-dropdown-panel-items"] [role="option"]',
  commentBox: '[class*="form-group"] textarea',
  informHolderBtn: '//button[contains(text(), "Inform Holder")]',
  successsfulyInformed: '//p[text()="Successfully Informed! "]',
  markPaidBtn: '//tbody//button[contains(text(), "Mark Paid")]',
  markPaidModal: '(//div[@class="right-sidebar right-sidebar-lg"])[3]',
  addAttachment: 'input[id="uploaddocuments"]',
  addAttachmentColumn: '(//div[@class="sidebar-content"]//tbody)[3]//tr//td[6]',
  proceedBtn: '//button[contains(text(), "Proceed")]',
  multipleMarkPaidBtn:
    '//div[@class="row mt-3"]//button[contains(text(), "Mark Paid")]',
  generateInvoiceBtn:
    '(//button[contains(@class, "btn")][contains(text(), "Generate Invoice")])[1]',
  downloadBtn: '//div//span[contains(text(), "Download")]',
  downloadBatchItem: '[class*="download-filter-dropdown"] button',
  noBankinDetail: '//tr//td[contains(text(), "-")]',
  dropdownOptions: '[class*=" dropdown-menu show"] li',
  taxInput: 'input[placeholder="Enter amount"]',
  taxValue: '[class="value clr-danger"]',
  editTaxModal: '(//div[@class="right-sidebar right-sidebar-lg"])[1]',
  tickIcon: '[class="fas fa-check-circle"]',
  modalMeatballBtn:
    '//div[@class="sidebar-content"]//div[@class="table-responsive"]//table//button[contains(@class, "dropdown-toggle")]',
  skippedTab: 'ngb-accordion[role="tablist"] button',
  skippedPayoutTable: '(//table[@role="table"])[2]',
  skippedMeatballBtn:
    '(//table)[2]//button[contains(@class, "dropdown-toggle")]',
  rescheduleModal:
    '(//div[@class="right-sidebar"]//div[@class="sidebar-content"])[2]',
  scheduleBtn: '//button[contains(text(), " Schedule Payout ")]',
  payoutTabs: 'li[routerlinkactive="active"]',
  holdersTable: "(//table//tbody)[1]",
  holdersName: "(//table//tbody)[1]//tr//td[2]",
  searchHolder: '(//input[@type="search"])[2]',
  holdersId: "(//table//tbody)[1]//tr//td[1]",
  holderPayoutHistory: '(//div[@class="right-sidebar right-sidebar-lg"])',
  historyTable: "(//table//tbody)[1]",
  modalWindow: '(//div[@class="right-sidebar right-sidebar-lg"])[1]',
  generateRenatalReportBtn:
    '//button[contains(text(), " Generate Rental Report ")]',
  rentalReportOption: '[class="show dropdown"] li button',
};
