export const transactionPage = {
  transactionTab: '//span[text()="Transactions"]',
  usersTab: '//span[text()="Users"]',
  heading: '[class*="heading"]',
  tableRow: '[class*="mat-row"]',
  createTransactionBtn: '//button[text()="Create Transaction "]',
  transactionMenu: '[class="right-sidebar"]',
  ppTransactionBtn: '//span[text()="Partner Plan Transactions "]',
  ptpTransactionBtn: '//span[text()="Peer to Peer Transactions "]',
  searchinvestor: '(//div[@class="search-dropdown"]//input)[1]',
  searchAgent: '(//div[@class="search-dropdown"]//input)[2]',
  investorsList: ".search-dropdown .users-list",
  agentList: ".search-dropdown .users-list",
  projectOption: '[aria-label="Options list"]',
  selectTransactionType: '[class*="reset-options "] button',
  transactionType: '[placeholder="Select transaction Type"]',
  transactionOption: '[role="option"]',
  selectRound: 'ng-select [class="ng-arrow"]',
  roundoption: '[role="option"]',
  areaInput: '(//div[@class="input-group"])[1]',
  rateAdjustInput: '(//div[@class="input-group"]//input)[2]',
  duedate: '[type="date"]',
  discountAmmount: '(//div[@class="select-input"]//input)[1]',
  agentCommesion: '(//div[@class="select-input"]//input)[2]',
  percentageBtn: '[class="select-input"] button',
  amount: ".il-items .il-item .value",
  proceedNextBtn: '//button[text()=" Proceed Next"]',
  createTransactionNow: '//button[text()=" Create Transaction Now "]',
  rate: '[class="mpd-item"] [class="value"]',
  transactionSuccess: ".sidebar-content-body .heading",
  transactionId: '[class="text mb-3"] b',
  sidebarCloseBtn: '[class*="panel-close-btn"]',
  transactionInstance: 'tbody[role="rowgroup"] tr',
  transactionDetail: '[class="trans-detail"] p',
  transactionTabs: '[class="mat-tab-labels"] [role="tab"]',
  searchPeer: '[class*="search-dropdown"]',
  peerAreaInput: '[formcontrolname="area"]',
  listBox: '[role="listbox"] [role="option"]',
  radioButton: '[role="radiogroup"]',
  navigationDrawer: '[class*="btn_IconOnly"]',
  toastMessage: '[class*="mat-snack-bar-container"]',
  inputGroup: '[class="input form-group"]',
  searchInput: '[class="main-panel"] input[type="search"]',
  updateTransactionBtn: '//button[text()=" Update Transaction "]',
  verifyTransactionBtn: '//button[text()=" Verify Transaction "]',
  updateStatusBtn: '//button[text()=" Update Status "]',
  daysFilterBtn: "#transaction-details .dropdown-toggle",
  daysFilterMenu: '[id="transaction-details"] [container="body"]',
  transactioIdIndex: "//tbody//tr//td[1]",
  actionDropdown: "//tbody//tr[1]//td//button",
  actionDropdownMenu: '[class="ngb-menu-body dropdown-menu show"]',
  addNote: '[class="input form-group"] textarea',
  discardTransactionBtm: '//button[text()=" Discard Transaction "]',
  addAgentInput: '[class="trans-status"] input',
  agentOption: ".users-list",
  addAgentBtn: '//button[text()=" Add Agent "]',
  notesinput: '[role="tabpanel"] textarea',
  notesBtn: '[role="tabpanel"] button',
  popupContainer: '[class*="mat-dialog-container"]',
  transactionDetailBtns: '[class="trans-detail"] button',
  documentTypedropdown: '[class="ng-arrow-wrapper"]',
  documentTypemenu: '[role="listbox"] span',
  uploadDocumentinput: 'input[id="uploaddocuments"]',
  documentUploaded: ".attachments .heading",
  updateAttachment: '//button[text()="Update Attachments "]',
  deleteFileBtn: '[class="file-upload-actions"] button',
  dropdownBtn: '[id*="panel-"] button',
  table: 'table[role="table"]',
  suspendedUserError: '//label[text()=" *User is suspended "]',
  tableHeader: '[role="columnheader"]',
  txnIDColumn: "//tbody//tr//td[1]",
  collapsBtn: '//button[text()=" Collapse All "]',
  expandBtn: '//button[text()=" Expand All "]',
  transactioLogBtn: '//div[contains(text(), "Transactions Log")]',
  transactionLogs:
    '[class="mat-tab-body-wrapper"] [class*="transactions-log "]',
  dropdownPanel: '[role="tablist"] [role="tabpanel"]',
  crossBtn: '[class="right-sidebar"] [class*=" btn-icon "]',
  backBtn: '//div[@class="right-sidebar"]//button[contains(text(), " Back ")]',
  userIDTableHeader: '(//th[@role="columnheader"])[4]',
  transactionFormDropdown: '[role="tabpanel"] [class="ng-arrow-wrapper"]',
  dropdownOption: '[class*="ng-dropdown-panel-items "] [role="option"]',
  proceedBtn: '//button[contains(text(), "Proceed")]',
  backToTransactionBtn: '//button[contains(text(), " Back to Transactions ")]',
};
