export const accessPage = {
  accessTab: '//span[text()="Access"]',
  addUserBtn: '//button[text()="Add User"]',
  userDetailForm: '(//div[@class="card app-card"]//form)[1]',
  projectRoleForm: 'form [class="ng-arrow-wrapper"]',
  userFormBtns: '[class="app-content"] button',
  userRoleOptions: '[role="option"]',
  imgupload: '[id="img-upload-preview"]',
  rolesCard: '[class*="app-card-border"]',
  detailsTitle: '[class="title"]',
  detailsValue: '[class="value"]',
  navigationDrawer: '[class*="btn_IconOnly"]',
  heading: '[class*="heading"]',
  tableRow: '[class*="mat-row"]',
  toastMessage: '[class*="mat-snack-bar-container"]',
  searchInput: 'input[type="search"]',
  meetballActionBtn: '[class="ngb-menu dropdown"] [class*="dropdown-toggle "]',
  actionBtn: '[class*=" dropdown-menu "] button',
  editUSerBtn: '//button[text()="Edit User"]',
  updateUserBtn: '//button[text()="Update User"]',
  popcontainer: '[class*="mat-dialog-container "]',
  tablist: '[class="mat-tab-labels"] [role="tab"]',
  resetOption: '[class="reset-options"] button',
  sendBtn: '//button[text()="Send"]',
  newPasswordInput: 'input[formcontrolname="newPassword"]',
  confirmPasswordInput: 'input[formcontrolname="confirmPassword"]',
  generatePasswordBtn: '//button[text()="Generate password"]',
  cancelBtn: '//button[contains (text() , "Cancel")]',
  unassignBtn: '//button[text()="Unassign Project"]',
  rightsideModal: '[class="right-sidebar"] [class*=" sidebar-content"]',
  accessTable: 'tbody[role="rowgroup"] tr',
  assignRoleBtn: '//button[text()="Assign New Project"]',
};
