export const activityPage = {
  ActivityLogTab: '//span[text()="Activity Log"]',
  filterDropdown: '[class*="ngb-filters-content"]',
  categoryFilter: '[class="ng-arrow-wrapper"]',
  categoryoptions: '[role="listbox"] [role="option"] input',
  applyBtn: '//button[text()=" Apply "]',
  resetBtn: '//button[text()=" Reset "]',
  activityTable: 'tbody[role="rowgroup"]',
  dateInput: 'input[type="date"]',
  clearFilterBtn: '//button[text()="Clear Filters"]',
  appliedFilter: '[class="applied-filters"]',
  projectFilter: 'button[class*="dropdown-toggle"]',
  projectDropdown: '[class*="dropdown-menu"]',
  projectFilterMenu: '[class="checkbox-column"] mat-checkbox',
  projectFilterApplyBtn: '//button[text()="Apply"]',
  verifyTransactionBtn: '//button[text()=" Verify Transaction "]',
  updateStatusBtn: '//button[text()=" Update Status "]',
  addPaymentsBtn: '//button[text()="Add Payment "]',
  expandAllBtn: '//button[text()=" Expand All "]',
  dropdownOption: '[role="option"]',
  amountRecievedInput: '[formcontrolname="amountReceived"]',
  // dateInput: '[formcontrolname="paymentDate"]',
  fileUploadBtn: '//label[text()="Browse"]',
  dueAmount: '[class="right-sidebar"] [class="text"]',
  fileUpload: 'input[id="fileDropRef"]',
  fileUploaded: '[class="right-sidebar"] [class="file-info"]',
  daysFilterBtn: "#transaction-details .dropdown-toggle",
  daysFilterMenu: '[id="transaction-details"] [container="body"]',
  transactioIdIndex: "//tbody//tr[1]//td[1]//div[2]",
  actionDropdown: "//tbody//tr[1]//td//button",
  actionDropdownMenu: '[class="ngb-menu-body dropdown-menu show"]',
  addNote: '[class="input form-group"] textarea',
  discardTransactionBtm: '//button[text()=" Discard Transaction "]',
  addAgentInput: '[class="trans-status"] input',
  agentOption: ".users-list",
  addAgentBtn: '//button[text()=" Add Agent "]',
  notesinput: '[role="tabpanel"] textarea',
  notesBtn: '[role="tabpanel"] button',
  noteText: '[role="tabpanel"] p',
  transactionDetailBtns: '[class="trans-detail"] button',
  documentTypedropdown: '[class="ng-arrow-wrapper"]',
  documentTypemenu: '[role="listbox"] span',
  uploadDocumentinput: 'input[id="uploaddocuments"]',
  documentUploaded: ".attachments .heading",
  deleteFileBtn: '[class="file-upload-actions"] button',
  updateAttachment: '//button[text()="Update Attachments "]',
  updateTransactionBtn: '//button[text()=" Update Transaction "]',
  sidebarMenu: '[class="right-sidebar"]',
  inputGroup: '[class="input form-group"]',
  filterBtn: '//button[text()="Filters "]',
  navigationDrawer: '[class*="btn_IconOnly"]',
  heading: '[class*="heading"]',
  searchInput: 'input[type="search"]',
  tableRow: '[class*="mat-row"]',
  table: 'table[role="table"]',
};
