export const docManagementPage = {
  docManagementTab: '//span[text()="Doc Management"]',
  createInvestmentPlanBtn: '//button[text()="Create Investment Plan"]',
  documentTabs: '[class="mat-tab-labels"] [role="tab"]',
  searchInputDropdown: '[class="search-dropdown"] input',
  formInput: 'form [class="ng-arrow"]',
  viewAndApproveBtn: '(//tbody[@role="rowgroup"]//tr[@role="row"])[4]//button',
  documentDetailBtn: '[class="right-panel"] button',
  documentDetail: '[class="right-panel"]',
  ppAprovalbtns: '[class="text-right btns-group"] button',
  discardBtn: '//div[@class="sidebar-content-body"]//button[text()="Discard"]',
  discardPlan: '//button[text()="Discard Plan"]',
  searchinvestorInput: '[formcontrolname="investor"]',
  currencyDropdown: ".d-flex .ng-arrow-wrapper",
  investmentPlanDropdown: '(//span[@class="ng-arrow-wrapper"])[2]',
  unitInput: 'input[formcontrolname="unit"]',
  unitItems: ".user-item",
  commentBox: '[formcontrolname="comment"]',
  requestApprovalBtn: '//button[text()="Request for Approval"]',
  proceedRequestBtn: '//button[text()="Proceed Request"]',
  investorList: ".search-dropdown .users-list .user-item",
  investmentAmountInput: '[formcontrolname="investmentAmount"]',
  usecaseIndex: "//tbody//tr//td[4]//span",
  attachmentIndex:
    "(//tbody[@role='rowgroup']//tr[@role='row']//td[@role='cell'])[11]",
  createUserBtn: '//button[text()="Create New User"]',
  textError: '[class*="text-error"]',
  navigationDrawer: '[class*="btn_IconOnly"]',
  heading: '[class*="heading"]',
  listBox: '[role="listbox"] [role="option"]',
  dropdownOption: '[role="option"]',
  dropdown: '[class="ng-arrow-wrapper"]',
  popupContainer: '[class*="mat-dialog-container"]',
  toastMessage: '[class*="mat-snack-bar-container"]',
  userNameInput: '[formcontrolname="legalName"]',
  emailInput: '[formcontrolname="email"]',
  phoneNoInput: '[formcontrolname="phoneNumber"]',
  cnicInput: '[formcontrolname="cnic"]',
  genderInput: '[formcontrolname="gender"]',
  investorsForm: '[class*="form-container"]',
  submitBtn: '//button[text()="Submit"]',
  searchInput: 'input[type="search"]',
  tabList: '[class="mat-tab-labels"]',
  sidebarMenu: '[class="right-sidebar"]',
  infiniteScroll: '[class*="search-results "]',
  yearlyReturnInput: '[formcontrolname="yearlyReturn"]',
  monthlySavingInput: '[formcontrolname="savingPerMonth"]',
  meetballBtn: '[class="right-panel"] button[class*="dropdown-toggle"]',
  meetballMenu: '[class*=" dropdown-menu "] button',
  tableRow: 'tbody[role="rowgroup"] tr',
  nextDocBtn: '//button[contains(text(), "Next Doc")]',
  docInvestorId: '[class="sidebar-content-body"] [class*="pill "]',
  tooltip: '[role="tooltip"]',
};
