export const loginPage = {
  loginform: '[class="mat-tab-body-wrapper"]',
  emailAddressTaB: '[aria-posinset="1"]',
  phoneNoTab: '[aria-posinset="2"]',
  otpTab: '[aria-posinset="3"]',
  matTab: '[class="mat-tab-label-content"]', // tab list elements
  emailInput: '[formcontrolname="email"]',
  passwordInput: '[formcontrolname="password"]',
  loginBtn: '//button[text()="Login"]',
  rememberMe: '[class="mat-checkbox-layout"]',
  toastMessage: '[class*="mat-snack-bar-container"]',
  emailEmptyField: '//label[text()="Email is required"]',
  heading: '[class*="heading"]',
  navigationDrawer: '[class*="btn_IconOnly"]',
  settingsTab: '//span[text()="Settings"]',
  editButton: '//button[text()="Edit"]',
  fullNameinput: '[formcontrolname="legalName"]',
  saveChangesBtn: '//button[text()="Save Changes"]',
  avatarIcon: 'button[class="dropdown-toggle"]',
  logOutBtn: '//button[text()="Logout"]',
  phoneNoInput: '[formcontrolname="phoneNumber"]',
  avatarMenu: '[class="user-details"]',
  switchAccount: '[class*="uil uil-exchange"]',
  investorLogo: '[class="wrapper"] [class="logo"]',
  investorAvatarIcon: '[class="menuDv"] [class="mat-menu-trigger"]',
  investerDropdown: '[class*="mat-menu-panel"]',
  dateInput: '[formcontrolname="DOB"]',
  currentPassword: '[formcontrolname="currentPassword"]',
  confirmPassword: '[formcontrolname="confirmPassword"]',
  newPassword: '[formcontrolname="newPassword"]',
  notificationToggle: '[class="mat-slide-toggle-bar"]',
  contactUsLable: '[class*="login-sec"] a',
  daoLogo: '[id="logo"]',
  navMenu: 'ul[id="top-menu"] li',
  imgImput: 'input[type="file"]',
};
