export const usersPage = {
  avatarIcon: 'button[class="dropdown-toggle"]',
  avatarMenu: '[class="user-details"]',
  logOutBtn: '//button[text()="Logout"]',
  createInvestorBtn: '//button[text()="Create Investor"]',
  usersTab: '//span[text()="Users"]',
  tabList: '[class="mat-tab-labels"]',
  leadstab: '[id="mat-tab-label-3-0"]',
  pledgeTab: '[id="mat-tab-label-3-1"]',
  investorsTab: '[id="mat-tab-label-3-2"]',
  searchInput: '[placeholder="Search"]',
  tableRow: '[class*="mat-row"]',
  userIDColumn: "//tbody//tr//td[1]",
  userNameInput: '[formcontrolname="legalName"]',
  phoneNoInput: '[formcontrolname="phoneNumber"]',
  nockNameInput: '[formcontrolname="nickName"]',
  dobInput: '[formcontrolname="DOB"]',
  cnicInput: '[formcontrolname="cnic"]',
  genderInput: '[formcontrolname="gender"]',
  additionalInformationBtn: '[aria-controls="panel-2"]',
  investorsForm: '[class*="form-container"]',
  submitBtn: '//button[text()="Submit"]',
  profileBackBtn: '[class*="btn-secondary"]',
  investorId: '[class*="pill-theme-light"]',
  editBtn: '//button[contains(text(), "Edit")]',
  cancelBtn: '//button[text()=" Cancel "]',
  updateBtn: '//button[text()="Update"]',
  switchAccount: '[class*="uil uil-exchange"]',
  investorLogo: '[class="wrapper"] [class="logo"]',
  investorAvatarIcon: '[class="menuDv"] [class="mat-menu-trigger"]',
  investerDropdown: '[class*="mat-menu-panel"]',
  userDropDownMenu: 'tbody [class*="dropdown-toggle"]',
  resetPasswordBtn: '//div[@class="dropdown"]//button[text()="Reset Password"]',
  passworResetMenu: '[class="right-sidebar"] [class="sidebar-content"]',
  suspendUserBtn: '//div[@class="dropdown"]//button[text()="Suspend User"]',
  sendBtn: '//button[text()="Send"]',
  newPasswordInput: '[formcontrolname="newPassword"]',
  confirmPasswordInput: '[formcontrolname="confirmPassword"]',
  generatePasswordBtn: '//button[text()="Generate password"]',
  popupContainer: '[class*="mat-dialog-container"]',
  suspendBtn: '//button[text()="Suspend"]',
  unsuspendUserBtn: '(//button[text()="Unsuspend User"])[1]',
  unsuspendBtn: '//button[text()="Unsuspend"]',
  emailInput: '[formcontrolname="email"]',
  toastMessage: '[class*="mat-snack-bar-container"]',
  heading: '[class*="heading"]',
  passwordInput: '[formcontrolname="password"]',
  loginBtn: '[type="submit"]',
  navigationDrawer: '[class*="btn_IconOnly"]',
  transactionInstance: 'tbody[role="rowgroup"] tr',
  transactionDetail: '[class="trans-detail"] p',
  verifyTransactionBtn: '//button[text()=" Verify Transaction "]',
  updateStatusBtn: '//button[text()=" Update Status "]',
  addPaymentBtn: '//button[text()="Add Payment "]',
  dropdown: '[class="ng-arrow-wrapper"]',
  listBox: '[role="listbox"]',
  menuOption: '[role="option"]',
  amountRecievedInput: '[formcontrolname="amountReceived"]',
  totalAmount: ".right-sidebar .input .text",
  dueDate: '[formcontrolname="paymentDate"]',
  uploadFile: 'input[type="file"]',
  uploadFile2: '(//input[@id="upload-file-icon"])[2]',
  noteInput: ' textarea[type="text"]',
  addEntryBtn: '//button[text()=" Add Entry "]',
  transactionTab: '//span[text()="Transactions"]',
  approveBtn: '//button[text()=" Approve Transaction "]',
  postblockchainBtn: '//button[text()=" Post On BlockChain "]',
  proceedBtn: '//button[text()=" Proceed "]',
  locktransactoionInput: '[placeholder="Password"]',
  doneBtn: '//button[text()=" Done "]',
  backToTransaction: '//button[text()=" Back to Transactions "]',
  transactionSearchinput: '[class="main-panel"] [type="search"]',
  nicknameInput: '[formcontrolname="nickName"]',
  tableHeader: '[role="columnheader"]',
  userNameColumn: "//tbody//tr//td[2]",
  userCreatedColumn: "//tbody//tr//td[3]",
  addBankAccountBtn: '//button[text()="Add Bank Account"]',
  addBankBtn: '//button[text()="Add Bank"]',
  accountTitleInput: '[formcontrolname="accountTitle"]',
  accountNumberinput: '[formcontrolname="accountNumber"]',
  ibanInput: '[formcontrolname="iban"]',
  checkbox: '[formcontrolname="checkbox"]',
  updaqteInfoBtn: '//button[contains(text(), "Update")]',
  legalInformationInput: '[class="card-body"] input',
  fileDropdownAction:
    '[class*="file-upload-actions"] [class*="dropdown-toggle"]',
  deleteBtn: '//button[contains(text(), "Delete")]',
  filingRadioBtn: '[role="radiogroup"] mat-radio-button',
  taxNumberInput: '(//input[@type="text"])[2]',
  nextOfKinForm: '[class="right-sidebar"] [class="sidebar-content"]',
  addNewKinBtn: '//button[text()="Add Next of kin"]',
  nameInput: 'input[formcontrolname="name"]',
  relattioInput: 'input[formcontrolname="relation"]',
  mobileInput: 'input[formcontrolname="mobile"]',
  addressInput: 'input[formcontrolname="address"]',
  distributionInput: 'input[formcontrolname="distribution"]',
  addKinBtn: '//button[text()="Add Next of Kin"]',
  kinCnic: 'input[formcontrolname="CNIC"]',
  meetballActionBtn: '[role="tab"] [class*="dropdown-toggle"]',
  updateKinBtn: '//button[text() = "Update Next of Kin"]',
  investordetailTabs: '[class*="Widget_TabUL"] ul li',
  newAddressBtn: '//button[text()="New Address "]',
  rightModalWindow: '[class="right-sidebar"]',
  addressLine1: 'input[formcontrolname="address1"]',
  addressLine2: 'input[formcontrolname="address2"]',
  cityInput: 'input[formcontrolname="city"]',
  countryInput: 'input[formcontrolname="country"]',
  addAddressBtn: '//button[text()="Add Address"]',
  addressCard: '[role="tablist"] [class*="card "]',
  updateaddressBtn: '//button[text()="Update Address "]',
  updateBankBtn: '//button[text()="Update Bank"]',
  bankActionBtn: '[class*="dropdown-toggle "]',
  clearFilterBtn: '//button[contains(text(), "Clear Filter")]',
  filterLabel: ".app-content .row .col-md-6 .justify-content-between",
  filterBtn: '[class="input-group"] [class*="filter-btn"]',
  filterMenu: '[class*="filter-container "] [class="card-body"]',
  addFilterBtn: '//div[contains(text(), "Add Filter")]',
  filterDropDown: '[class="dropdown"]',
  filterCheck: '[class="dropdown"] [class="mat-checkbox-layout"]',
  filterCategory: ".card-body .swiper-slide .app-ngbDropdown",
  dateInput: 'input[type="date"]',
  applyBtn:
    '//div[@class="btns-group text-right"]//button[contains(text(), "Apply")]',
  saveFilterBtn: '//div[contains(text(), "Save Filter")]',
  filterNameInput: '[class="form-group input"] input[type="text"]',
  defaultFilter: '[class="form-group input"] [class="ng-arrow-wrapper"]',
  filterOption: '[role="option"]',
  saveBtn: '//div[@class="dropdown"]//div//button[contains(text(), "Save")]',
  savedFilterBtn: '//div[contains(text(), "Saved Filters")]',
  filtersdropdownBtn: '[class*="filter-container"] [class*="dropdown-toggle"]',
  savedFilterItems: '[class="dropdown"] [class="dropdown-item"]',
  areaInput: '[class="dropdown"] [class="input-group"] input',
  filterTabs: '[class*=" filters-tabs "] [role="tab"]',
  searchResult: '[class*="filters-search-results "]',
  meetballMenu: '[class*=" dropdown-menu "]',
  clearFilterLabel: '//p[contains(text(), "Clear Filter")]',
  noResultFound: '//p[contains(text(), "No Result Found")]',
  recentSearch: ".dd-search .mat-tab-body-wrapper",
  closeBtn: '[class="sidebar-content-header"] [class*=" panel-close-btn"]',
};
